# Generated by Django 4.2 on 2023-04-27 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_criticality_managedby_softwaretype_vendor_software'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='media/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.documentcategory')),
                ('criticality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.criticality')),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.managedby')),
            ],
        ),
    ]
