# Generated by Django 4.2 on 2023-04-27 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_documentcategory_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='document/'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('service_tag', models.CharField(max_length=8, unique=True)),
                ('criticality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.criticality')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.document')),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.managedby')),
            ],
        ),
    ]
