# Generated by Django 4.2 on 2023-04-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_document_type_status_alter_document_file_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document_Type',
        ),
    ]
