# Generated by Django 4.2 on 2023-04-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_service_status_alter_service_service_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('billing_no', models.PositiveIntegerField()),
                ('serial_no', models.PositiveIntegerField()),
                ('purchase_price', models.PositiveIntegerField()),
                ('criticality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.criticality')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.document')),
                ('hardware_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.hardwaretype')),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.managedby')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.status')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.vendor')),
            ],
        ),
    ]
