# Generated by Django 4.2 on 2023-04-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_hardwaretype_hardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
