# Generated by Django 4.2 on 2023-04-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('insurance_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('premium_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('insurance_date', models.DateField()),
                ('maturity_time', models.CharField(choices=[('1', '1 month'), ('3', '3 months'), ('6', '6 months'), ('12', '12 months')], max_length=2)),
                ('payment_time', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Yearly', 'Yearly')], max_length=20)),
            ],
        ),
    ]
