# Generated by Django 4.2 on 2023-04-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_hardware_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.insurance'),
        ),
    ]
