# Generated by Django 4.2 on 2023-04-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_branchstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('branch_incharge_name', models.CharField(max_length=100)),
                ('branch_incharge_phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('established_year', models.PositiveIntegerField()),
                ('website', models.URLField(blank=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.country')),
                ('departments', models.ManyToManyField(to='blog.managedby')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.state')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.branchstatus')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
