# Generated by Django 4.2 on 2023-04-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_organization_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_details',
            name='branches',
            field=models.TextField(default=None, editable=False),
            preserve_default=False,
        ),
    ]
