# Generated by Django 4.2 on 2023-05-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_hardware_vendor_alter_software_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='full_name',
            field=models.CharField(default=None, help_text='Enter the name of vendor', max_length=255, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
