# Generated by Django 4.2 on 2023-05-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_vendor_name_vendor_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vat_pan',
            field=models.CharField(default=None, max_length=50, verbose_name='VAT/PAN'),
            preserve_default=False,
        ),
    ]
