# Generated by Django 4.2 on 2023-05-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_vendor_vat_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(default=None, max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
