# Generated by Django 4.2 on 2023-05-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_vendor_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='document_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Document Link'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner Name'),
        ),
    ]
