# Generated by Django 4.2 on 2023-05-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_vendor_description_vendor_document_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default=None, max_length=20, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
