# Generated by Django 4.2 on 2023-05-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_vendor_email_alter_vendor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='owner_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner Address'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Owner Email'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_id_file',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_proofs/', verbose_name='Owner ID File'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_id_type',
            field=models.CharField(blank=True, choices=[('citizenship', 'Citizenship'), ('passport', 'Passport'), ('voter_id', 'Voter ID')], max_length=20, null=True, verbose_name='Owner ID Type'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Owner Phone'),
        ),
    ]
