# Generated by Django 4.2 on 2023-05-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_vendor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedby',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='managedby',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
