# Generated by Django 4.2 on 2023-05-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_managedby_addto_alter_managedby_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managedby',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.RemoveField(
            model_name='managedby',
            name='Addto',
        ),
        migrations.AlterField(
            model_name='managedby',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Departments'),
        ),
    ]
