# Generated by Django 4.2 on 2023-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_managedby_options_remove_managedby_addto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedby',
            name='addtobranch',
            field=models.ManyToManyField(blank=True, to='blog.branch'),
        ),
    ]
