# Generated by Django 4.2 on 2023-05-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_alter_managedby_code_alter_managedby_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
