# Generated by Django 4.2 on 2023-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_alter_country_options_alter_hardware_hardware_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
