# Generated by Django 4.2 on 2023-05-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
