# Generated by Django 4.2 on 2023-05-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_issue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Service', 'Service'), ('Software', 'Software'), ('Document', 'Document')], max_length=10)),
                ('asset_name', models.CharField(max_length=255)),
                ('tentative_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Request', 'Request'), ('Approve', 'Approve'), ('Cancel', 'Cancel')], max_length=10)),
                ('status', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.managedby')),
            ],
        ),
    ]
