# Generated by Django 4.2 on 2023-05-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_software_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.branch'),
        ),
    ]
