# Generated by Django 4.2 on 2023-05-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_document_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='branch',
        ),
    ]
