# Generated by Django 4.2 on 2023-05-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_remove_asset_hardware_asset_hardware_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
