# Generated by Django 4.2 on 2023-05-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hardware_value',
            field=models.BooleanField(default=True),
        ),
    ]
