# Generated by Django 4.2 on 2023-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0064_asset_hardware_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='software_value',
            field=models.BooleanField(default=True),
        ),
    ]
