# Generated by Django 4.2.1 on 2023-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_rename_hardware_value_asset_dashboard_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
